# Numpy

In [ ]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
arr1 = np.array(range(10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2 = np.array([0.1,0.2,0.3])
arr2

array([0.1, 0.2, 0.3])

In [7]:
arr3 = np.array(['a','b','c'])
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [9]:
arr4 = np.array([1,2,'a','b',0.1,0.2])
arr4 # 모두 string 타입으로 통일 되었다.

array(['1', '2', 'a', 'b', '0.1', '0.2'], dtype='<U11')

In [14]:
arr5 = np.array([1,2,0.3,0.4])
arr5
# 모두 실수 타입으로 바뀌었다.

array([1. , 2. , 0.3, 0.4])

In [17]:
arr6 = np.array(
        [[1,2,3],
        [4,5,6],
        [7,8,9]])
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## array의 타입

In [18]:
arr1.dtype

dtype('int32')

In [20]:
arr2.dtype

dtype('float64')

In [21]:
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [22]:
arr3.dtype

dtype('<U1')

In [24]:
print(arr4.dtype)
arr4

<U11


array(['1', '2', 'a', 'b', '0.1', '0.2'], dtype='<U11')

In [25]:
print(arr5.dtype)
arr5

float64


array([1. , 2. , 0.3, 0.4])

In [26]:
print(arr6.dtype)
arr6

int32


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### shape

배열의 형태를 나타내줌

In [28]:
arr5

array([1. , 2. , 0.3, 0.4])

In [30]:
arr5.shape

(4,)

In [31]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr6.shape

(3, 3)

### arage, linspace

In [35]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr2 = np.arange(3,13)
arr2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
arr3 = np.arange(5.0)
arr3

array([0., 1., 2., 3., 4.])

In [43]:
arr4 = np.arange(3,100,3.0)
arr4

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39.,
       42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72., 75., 78.,
       81., 84., 87., 90., 93., 96., 99.])

linspace

In [47]:
np.linspace(-5, 5, 10)

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

### reshape(배열의 형태 변환)

In [50]:
arr = np.arange(36.0)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [52]:
arr.shape

(36,)

In [53]:
arr2 = arr.reshape(12,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.],
       [30., 31., 32.],
       [33., 34., 35.]])

In [54]:
arr2.shape

(12, 3)

In [56]:
#3차원 배열
arr3 = arr.reshape(3,4,3)
print(arr3.shape)
arr3

(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [58]:
print(arr1.shape)
arr1

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr1.shape = (5,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [62]:
# shape
print(arr3.shape)
arr3

(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [63]:
arr3.reshape(-1,12) 

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.]])

In [64]:
arr3.reshape(-1) 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [66]:
arr3.reshape(4,-1,3) # 4개로 1행당 3개씩

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]],

       [[27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

### astype - 배열의 dtype을 변환

In [72]:
arr1 = np.arange(5)
arr2 = np.arange(0.0,0.5,0.1)
arr1, arr2

(array([0, 1, 2, 3, 4]), array([0. , 0.1, 0.2, 0.3, 0.4]))

In [73]:
print(arr1.dtype)
print(arr2.dtype)

int32
float64


In [76]:
#int -> float
print(arr1.astype(float))
print(arr1.astype(np.float64))

[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]


In [78]:
# float ->string
print(arr2.astype(str))
print(arr2.astype(np.str))

['0.0' '0.1' '0.2' '0.30000000000000004' '0.4']
['0.0' '0.1' '0.2' '0.30000000000000004' '0.4']


## rand

### rand

In [81]:
np.random.rand(5)

array([0.73203479, 0.55723917, 0.09251575, 0.89093666, 0.3810108 ])

In [82]:
np.random.rand(3,3)

array([[0.34805467, 0.07205044, 0.12151195],
       [0.58749633, 0.98542769, 0.80621393],
       [0.4499299 , 0.9597277 , 0.8337597 ]])

In [83]:
np.random.rand(2,2,2)

array([[[0.63697734, 0.54260809],
        [0.05389826, 0.96211314]],

       [[0.33566695, 0.12394068],
        [0.68889549, 0.17541436]]])

### randint

In [85]:
np.random.randint(-5,3,(3,3)) # -5~3까지 중 3*3배열로..

array([[ 0,  1,  0],
       [ 2, -5,  0],
       [-3, -4, -2]])

### randn

In [86]:
np.random.randn(2,5)

array([[ 1.02792019, -0.18421638, -1.14710804, -0.48148756,  2.47872316],
       [ 0.51020912, -0.36879015,  1.00005173,  0.18334959,  0.46981074]])

### array의 indexing, Slicing

In [89]:
arr1 = np.arange(0, 100, 10.0)
arr1

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [94]:
arr1[0], arr1[1],arr1[2]

(0.0, 10.0, 20.0)

In [97]:
arr1[:], arr1[4:], arr1[1:],arr1[1:8]

(array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]),
 array([40., 50., 60., 70., 80., 90.]),
 array([10., 20., 30., 40., 50., 60., 70., 80., 90.]),
 array([10., 20., 30., 40., 50., 60., 70.]))

In [98]:
arr1[::2],arr1[::3]

(array([ 0., 20., 40., 60., 80.]), array([ 0., 30., 60., 90.]))

#### n-Dim array indexing, Slicing

In [107]:
#2차원 배열0~23, (8,3)
arr2 = np.arange(24.0).reshape(8,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [109]:
arr2[4]

array([12., 13., 14.])

In [115]:
print(arr2[3][1]) #성능 느림
print(arr2[3,1])  #Standard Case on Numpy

10.0
10.0


In [121]:
print(arr2[3,1:])
print(arr2[3:,1:])
print(arr2[::2,:])

[10. 11.]
[[10. 11.]
 [13. 14.]
 [16. 17.]
 [19. 20.]
 [22. 23.]]
[[ 0.  1.  2.]
 [ 6.  7.  8.]
 [12. 13. 14.]
 [18. 19. 20.]]


In [124]:
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [132]:
print(arr2[[0,5,3]])
print(arr2[[0,5,3],[1]])

[[ 0.  1.  2.]
 [15. 16. 17.]
 [ 9. 10. 11.]]
[ 1. 16. 10.]


In [134]:
arr2[arr2>10]

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [135]:
arr2[arr2%2==1]

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.])

### numpy의 상수

In [136]:
arr = np.array([1,2,3,np.nan,np.inf,-np.inf])
print('dtype: ', arr.dtype)
arr

dtype:  float64


array([  1.,   2.,   3.,  nan,  inf, -inf])

## arr의 연산

In [137]:
arr1 = np.arange(0,10,1)
arr2 = np.arange(1,0,-0.1)
arr1, arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]))

In [143]:
#array와 scalar 연산
print(arr1 + 1)
print(arr1 - 1)
print(arr1 * 10)
print(arr1 / 10)
print(arr1 ** 2)
print(arr1 % 2)

[ 1  2  3  4  5  6  7  8  9 10]
[-1  0  1  2  3  4  5  6  7  8]
[ 0 10 20 30 40 50 60 70 80 90]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 0 1 0 1 0 1 0 1]


In [145]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** arr2)
print(arr1 % arr2)

[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]
[-1.   0.1  1.2  2.3  3.4  4.5  5.6  6.7  7.8  8.9]
[0.  0.9 1.6 2.1 2.4 2.5 2.4 2.1 1.6 0.9]
[ 0.          1.11111111  2.5         4.28571429  6.66666667 10.
 15.         23.33333333 40.         90.        ]
[0.         1.         1.74110113 2.15766928 2.29739671 2.23606798
 2.04767251 1.79278996 1.51571657 1.24573094]
[0.  0.1 0.4 0.2 0.4 0.5 0.4 0.1 0.2 0.1]


In [146]:
arr1 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [147]:
arr1 >arr2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## 행렬

In [148]:
#0행령
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [149]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 일행렬

In [150]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [151]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 단위행렬

In [153]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [155]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [156]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [157]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 통계를 위한 연산

In [160]:
arr1 = np.arange(1,11.0).reshape(5,2)
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

### sum

In [161]:
arr1.sum()

55.0

In [164]:
arr1.sum(axis=0) #행단위

array([25., 30.])

In [165]:
arr1.sum(axis=1) #열단위

array([ 3.,  7., 11., 15., 19.])

### mean

In [166]:
arr1.mean()

5.5

In [170]:
arr1.mean(axis=0)

array([5., 6.])

In [171]:
arr1.mean(axis=1)

array([1.5, 3.5, 5.5, 7.5, 9.5])

### var

In [172]:
arr1.var()

8.25

In [173]:
arr1.var(axis=0)

array([8., 8.])

In [175]:
arr1.var(axis=1)

array([0.25, 0.25, 0.25, 0.25, 0.25])

### std

In [176]:
arr1.std()

2.8722813232690143

In [177]:
arr1.std(axis=0)

array([2.82842712, 2.82842712])

In [178]:
arr1.std(axis=1)

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [180]:
np.sqrt(arr1.var(axis=1))

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [181]:
np.log(arr1) # 로그

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.60943791, 1.79175947],
       [1.94591015, 2.07944154],
       [2.19722458, 2.30258509]])

In [182]:
np.exp(arr1) #지수

array([[2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04]])

In [183]:
2.5e+3

2500.0

### min

In [185]:
print(arr1.min())
print(arr1.min(axis=0))
print(arr1.min(axis=1))

1.0
[1. 2.]
[1. 3. 5. 7. 9.]


### max

In [186]:
print(arr1.max())
print(arr1.max(axis=0))
print(arr1.max(axis=1))

10.0
[ 9. 10.]
[ 2.  4.  6.  8. 10.]


### consum

In [187]:
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [190]:
print(arr1.cumsum())
print(arr1.cumsum(axis=0))
print(arr1.cumsum(axis=1))

[ 1.  3.  6. 10. 15. 21. 28. 36. 45. 55.]
[[ 1.  2.]
 [ 4.  6.]
 [ 9. 12.]
 [16. 20.]
 [25. 30.]]
[[ 1.  3.]
 [ 3.  7.]
 [ 5. 11.]
 [ 7. 15.]
 [ 9. 19.]]


### cumprod

In [191]:
print(arr1.cumprod())
print(arr1.cumprod(axis=0))
print(arr1.cumprod(axis=1))

[1.0000e+00 2.0000e+00 6.0000e+00 2.4000e+01 1.2000e+02 7.2000e+02
 5.0400e+03 4.0320e+04 3.6288e+05 3.6288e+06]
[[1.00e+00 2.00e+00]
 [3.00e+00 8.00e+00]
 [1.50e+01 4.80e+01]
 [1.05e+02 3.84e+02]
 [9.45e+02 3.84e+03]]
[[ 1.  2.]
 [ 3. 12.]
 [ 5. 30.]
 [ 7. 56.]
 [ 9. 90.]]


In [194]:
arr1 = np.arange(1,7).astype(np.float64).reshape(2,3)
arr2 = np.arange(6,0,-1.0).astype(np.float64).reshape(3,2)
arr1, arr2

(array([[1., 2., 3.],
        [4., 5., 6.]]), array([[6., 5.],
        [4., 3.],
        [2., 1.]]))

In [195]:
arr1.shape, arr2.shape

((2, 3), (3, 2))

In [196]:
arr1 @ arr2

array([[20., 14.],
       [56., 41.]])

In [197]:
arr1.dot(arr2)

array([[20., 14.],
       [56., 41.]])

In [198]:
np.matmul(arr1,arr2)

array([[20., 14.],
       [56., 41.]])

### 전치

In [199]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [202]:
arr3 = np.arange(6).reshape(2,3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [203]:
arr1.shape, arr3.shape

((2, 3), (2, 3))

In [205]:
arr3.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [206]:
arr3.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [207]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [210]:
arr1 = np.arange(1,5).reshape(2,2)
arr1

array([[1, 2],
       [3, 4]])

In [211]:
arr2 =np.linalg.inv(arr1)
arr2

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [212]:
arr1.dot(arr2)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [213]:
arr2.dot(arr1)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

## concat

In [214]:
arr1 = np.arange(4).reshape(2,2)
arr2 = np.arange(0,40,10).reshape(2,2)
arr1, arr2

(array([[0, 1],
        [2, 3]]), array([[ 0, 10],
        [20, 30]]))

In [215]:
np.concatenate((arr1, arr2),axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 0, 10],
       [20, 30]])

In [216]:
np.c_[arr1,arr2]

array([[ 0,  1,  0, 10],
       [ 2,  3, 20, 30]])

# 연습문제

1. 10개의 0백터를 만들고 4번째와 5번재 index의 값을 1로 한후 (5,2)행렬로 만들어라. 

In [221]:
arr1 = np.zeros(10)
arr1[3] = 1
arr1[4] = 1
arr1 = arr1.reshape(5,2)
arr1

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.]])

2. 10에서 30까지 2씩 증가하는 vector를 만들고 다음 list와 요소별 사칙연산(+,-,*,/)을 하여라

In [224]:
vect1 = np.arange(10,31,2)
vect1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [226]:
print(vect1+vect1)
print(vect1-vect1)
print(vect1*vect1)
print(vect1/vect1)

[20 24 28 32 36 40 44 48 52 56 60]
[0 0 0 0 0 0 0 0 0 0 0]
[100 144 196 256 324 400 484 576 676 784 900]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3. <1에서 100까지> 10개를 균등하게 분할하여 배열을 만들고, 각각의 합, 평균, 표준편차, 분산, 최소값,최대값, 누적합, 누적곱을 구하여라.

In [276]:
arr2 = np.linspace(1,100,10)
arr2

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [277]:
print(arr2.sum())
print(arr2.mean())
print(arr2.std())
print(arr2.var())
print(arr2.min())
print(arr2.cumsum())
print(arr2.cumprod())

505.0
50.5
31.595094555959157
998.25
1.0
[  1.  13.  36.  70. 115. 171. 238. 316. 405. 505.]
[1.00000000e+00 1.20000000e+01 2.76000000e+02 9.38400000e+03
 4.22280000e+05 2.36476800e+07 1.58439456e+09 1.23582776e+11
 1.09988670e+13 1.09988670e+15]


4. 0에서 10까지 random한 값을 지닌 3*3실수 행렬을 만들어라

In [289]:
np.random.seed(42)
arr3 = np.random.rand(3,3)
arr3 = arr3 * 10
arr3

array([[3.74540119, 9.50714306, 7.31993942],
       [5.98658484, 1.5601864 , 1.5599452 ],
       [0.58083612, 8.66176146, 6.01115012]])

5. 0에서 10까지 random한 값을 지닌 3*3 정수 행렬을 만들어라

In [293]:
arr4 = np.random.randint(0,10,(3,3))
arr4

array([[7, 2, 5],
       [4, 1, 7],
       [5, 1, 4]])

6. 5x2행렬을 만들고 정규화 하여라.

In [304]:
#arr5 = np.arange(10).reshape(5,2).astype(np.float64)
arr5 = np.linspace(-1000,1000,5)
arr5 = arr5.reshape(5,-1)
arr5_1=np.linspace(0,10,5)
arr5_1 = arr5_1.reshape(5,-1)
arr5_2 =np.concatenate((arr5,arr5_1),axis=1)
arr5_2

array([[-1000. ,     0. ],
       [ -500. ,     2.5],
       [    0. ,     5. ],
       [  500. ,     7.5],
       [ 1000. ,    10. ]])

In [306]:
arr5.std() ,arr5_1.std()

(707.1067811865476, 3.5355339059327378)

In [308]:
arr5_2 = (arr5_2 - arr5_2.mean(axis=0)) /arr5_2.std(axis=0)
arr5_2

array([[-1.41421356, -1.41421356],
       [-0.70710678, -0.70710678],
       [ 0.        ,  0.        ],
       [ 0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356]])

 7.5x2 행렬을 만들고 Min-Max정규화(Nomalization) 하여라

In [310]:
arr6 = (arr5_2 - arr5_2.min(axis=0))/(arr5_2.max(axis=0)-arr5_2.min(axis=0))

arr6

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])