In [1]:
import tensorflow as tf

In [5]:
print(tf.__version__)

2.3.0


In [3]:
#딥러닝을 구동하는데 필요한 캐라스 함수들
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#필요한 라이브러리
import numpy as np
import tensorflow as tf

In [4]:
# 실행할 때마다 같은 결과를 출력하기 위해 설정하는 부분
np.random.seed(3)
tf.random.set_seed(3)

#준비된 수술 환자 데이터
Data_set = np.loadtxt("./dataset/ThoraricSurgery.csv",delimiter=",")
Data_set

AttributeError: module 'tensorflow._api.v1.random' has no attribute 'set_seed'

In [29]:
#환자의 기록과 수술 결과를 x와 y로 구분하여 저장
X = Data_set[:,0:17]  ###속성###
Y= Data_set[:,17]  ###클래스###

#딥러닝 구조 결정
model = Sequential()
model.add(Dense(30,input_dim=17, activation='relu'))
model.add(Dense(1,activation='sigmoid'))

# # 딥러닝 실행
model.compile(loss='mean_squared_error',optimizer='adam',metrics=['accuracy'])
model.fit(X,Y,epochs=100, batch_size=10)

# #결과를 출력
print('\n Accuracy: %.4f' % (model.evaluate(X,Y)[1]))

Epoch 1/100
47/47 [==============================] - 0s 589us/step - loss: 0.4234 - accuracy: 0.5553
Epoch 2/100
47/47 [==============================] - 0s 539us/step - loss: 0.1695 - accuracy: 0.8234
Epoch 3/100
47/47 [==============================] - 0s 650us/step - loss: 0.1487 - accuracy: 0.8511
Epoch 4/100
47/47 [==============================] - 0s 644us/step - loss: 0.1485 - accuracy: 0.8511
Epoch 5/100
47/47 [==============================] - 0s 615us/step - loss: 0.1479 - accuracy: 0.8511
Epoch 6/100
47/47 [==============================] - 0s 637us/step - loss: 0.1473 - accuracy: 0.8511
Epoch 7/100
47/47 [==============================] - 0s 618us/step - loss: 0.1465 - accuracy: 0.8511
Epoch 8/100
47/47 [==============================] - 0s 602us/step - loss: 0.1474 - accuracy: 0.8426
Epoch 9/100
47/47 [==============================] - 0s 609us/step - loss: 0.1476 - accuracy: 0.8511
Epoch 10/100
47/47 [==============================] - 0s 657us/step - loss: 0.1465 - accura

# Numpy

In [30]:
import numpy as np

In [31]:
ar = np.array([1,2,3,4,5,6,7,8,9])
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
ar2 = np.arange(10)
print(ar2.shape)
ar2

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
ar2.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
arr1 = np.arange(10,90,10)
arr1 = arr1.reshape(2,4)
arr1

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [54]:
arr1 = np.arange(1,25,1)
arr1 = arr1.reshape(3,4,2)
arr1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [56]:
arr1[0,0,1]

2

In [58]:
arr1[-1,-1,-1]

24

In [61]:
arr1[1,3,:]

array([15, 16])

In [66]:
arr2 = np.arange(0,15,1)
arr2 = arr2.reshape(3,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
arr2[1,2]

7

In [68]:
arr2[-1,-1]

14

In [70]:
arr2[1,1:3]

array([6, 7])

In [72]:
arr2[1:3,2]

array([ 7, 12])

In [73]:
arr2[0:2,3:5]

array([[3, 4],
       [8, 9]])

In [76]:
a = np.arange(10)
idx = np.array([True,False,True,False,True,False,True,False,True,False])
a[idx]

array([0, 2, 4, 6, 8])

In [77]:
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [78]:
a %2 ==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [79]:
x = np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [81]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [82]:
x[x% 4 == 1]

array([ 1,  5,  9, 13, 17])

In [90]:
x = np.array([1,2,3], dtype="f")
x

array([1., 2., 3.], dtype=float32)

In [91]:
x = np.array([1,2,3], dtype="U")
x

array(['1', '2', '3'], dtype='<U1')

In [92]:
np.array([0,1,-1,0])/np.array([1,0,0,0])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

In [93]:
np.log(0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [94]:
np.exp(-np.inf)

0.0

In [96]:
a= np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [100]:
b = np.zeros((5,2))
b

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [102]:
g = np.empty((4,3))
g

array([[1.47199061e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.49115331e-067],
       [2.62522719e+179, 5.21735529e-037, 1.74171409e+184],
       [2.23036065e+180, 4.85259998e-033, 1.51238088e+160]])

In [103]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [104]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [106]:
arr1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [108]:
arr1.T

array([[[ 1,  9, 17],
        [ 3, 11, 19],
        [ 5, 13, 21],
        [ 7, 15, 23]],

       [[ 2, 10, 18],
        [ 4, 12, 20],
        [ 6, 14, 22],
        [ 8, 16, 24]]])

In [133]:
a1 = np.ones((3,3))

a2 = np.zeros((3,3))
a1,a2

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [132]:
np.vstack([a1,a2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [140]:
np.tile(a1,(1,2))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [143]:
x=np.arange(3)
y= np.arange(3)

In [150]:
X,Y = np.meshgrid(x,y)

import time

In [154]:
x = np.arange(1,10001)
y = np.arange(10001,20001)

z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [153]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]
    

Wall time: 3.99 ms


In [159]:
x = np.arange(0,10)
x = x*100
x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [178]:
x = np.arange(1,7)
x = x.reshape(2,3)
x

y = np.array([1,10,100,1000,1000,100000]) * 10
y.reshape(2,3)

x

array([[1, 2, 3],
       [4, 5, 6]])

In [191]:
x.sort(axis=0)
x
np.savetxt('./dataset/a.txt', x)

In [190]:
import pandas as pd
a = np.loadtxt('./dataset/wine.csv', delimiter= ",")
a = pd.DataFrame(a)
a

0     1     2    3      4     5      6        7     8     9    10  \
0      7.4  0.70  0.00  1.9  0.076  11.0   34.0  0.99780  3.51  0.56   9.4   
1      7.8  0.88  0.00  2.6  0.098  25.0   67.0  0.99680  3.20  0.68   9.8   
2      7.8  0.76  0.04  2.3  0.092  15.0   54.0  0.99700  3.26  0.65   9.8   
3     11.2  0.28  0.56  1.9  0.075  17.0   60.0  0.99800  3.16  0.58   9.8   
4      7.4  0.70  0.00  1.9  0.076  11.0   34.0  0.99780  3.51  0.56   9.4   
...    ...   ...   ...  ...    ...   ...    ...      ...   ...   ...   ...   
6492   6.2  0.21  0.29  1.6  0.039  24.0   92.0  0.99114  3.27  0.50  11.2   
6493   6.6  0.32  0.36  8.0  0.047  57.0  168.0  0.99490  3.15  0.46   9.6   
6494   6.5  0.24  0.19  1.2  0.041  30.0  111.0  0.99254  2.99  0.46   9.4   
6495   5.5  0.29  0.30  1.1  0.022  20.0  110.0  0.98869  3.34  0.38  12.8   
6496   6.0  0.21  0.38  0.8  0.020  22.0   98.0  0.98941  3.26  0.32  11.8   

       11   12  
0     5.0  1.0  
1     5.0  1.0  
2     5.0  1.0  
3     6.0  1.0  
4     5.0  1.0  
...   ...  ...  
6492  6.0  0.0  
6493  5.0  0.0  
6494  6.0  0.0  
6495  7.0  0.0  
6496  6.0  0.0  

[6497 rows x 13 columns]